-- =============================================================================
-- Career Intelligence and Job Analytics Platform
-- PostgreSQL 14+ Schema — FIXED for direct CSV loading with explicit IDs
-- Student: Rutvi Chirag Patel | ZDA24B008 | Z2004 DBMS
--
-- FIX APPLIED: Changed "GENERATED ALWAYS AS IDENTITY" to
-- "GENERATED BY DEFAULT AS IDENTITY" on every primary key.
-- Reason: our CSVs already contain explicit primary key values
-- (user_id, job_id, skill_id, etc.) carried over from the data
-- pipeline. "ALWAYS" forbids inserting/copying explicit values
-- without a special OVERRIDING SYSTEM VALUE clause; "BY DEFAULT"
-- allows our CSV's existing IDs to load directly via \copy, while
-- still auto-generating IDs for any future manual INSERTs.
--
-- Run as: psql -d career_intelligence -f schema_postgres_fixed.sql
-- =============================================================================

BEGIN;

DROP TABLE IF EXISTS market_trends CASCADE;
DROP TABLE IF EXISTS job_skills CASCADE;
DROP TABLE IF EXISTS job_listings CASCADE;
DROP TABLE IF EXISTS education CASCADE;
DROP TABLE IF EXISTS user_skills CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS proficiency_level CASCADE;
DROP TYPE IF EXISTS requirement_level CASCADE;

-- ENUMs for constrained values
CREATE TYPE proficiency_level AS ENUM ('Expert', 'Advanced', 'Intermediate', 'Beginner');
CREATE TYPE requirement_level AS ENUM ('Required', 'Preferred', 'Nice-to-have');

CREATE TABLE users (
    user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name text,
    email text UNIQUE,
    location text,
    years_experience integer,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE companies (
    company_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name text,
    industry text,
    size_range text,
    hq_location text
);

CREATE TABLE skills (
    skill_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    skill_name text UNIQUE,
    category text
);

CREATE TABLE user_skills (
    user_skill_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    skill_id integer NOT NULL REFERENCES skills(skill_id) ON DELETE CASCADE,
    proficiency_level proficiency_level,
    acquired_date date
);

CREATE TABLE education (
    education_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    institution text,
    degree text,
    field_of_study text,
    graduation_year integer
);

CREATE TABLE job_listings (
    job_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id integer REFERENCES companies(company_id) ON DELETE SET NULL,
    title text,
    location text,
    salary_min numeric,
    salary_max numeric,
    employment_type text,
    description text,
    posted_date date,
    is_active boolean DEFAULT true
);

CREATE TABLE job_skills (
    job_skill_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_id integer NOT NULL REFERENCES job_listings(job_id) ON DELETE CASCADE,
    skill_id integer NOT NULL REFERENCES skills(skill_id) ON DELETE CASCADE,
    requirement_level requirement_level
);

CREATE TABLE market_trends (
    trend_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    skill_id integer REFERENCES skills(skill_id) ON DELETE CASCADE,
    recorded_month date,
    demand_score integer,
    avg_salary numeric,
    trend_direction text
);

-- Indexes (baseline — additional performance indexes added in performance.sql)
CREATE INDEX ix_user_skills_user_id ON user_skills(user_id);
CREATE INDEX ix_user_skills_skill_id ON user_skills(skill_id);
CREATE INDEX ix_job_skills_job_id ON job_skills(job_id);
CREATE INDEX ix_job_skills_skill_id ON job_skills(skill_id);
CREATE INDEX ix_job_listings_company_id ON job_listings(company_id);
CREATE INDEX ix_market_trends_skill_id ON market_trends(skill_id);

COMMIT;
